site_name: AddressMatchPro
theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: api-reference.md
  - Contributing: contributing.md

markdown_extensions:
  - codehilite
  - toc:
      permalink: true

extra_css:
  - css/custom.css

extra_javascript:
  - js/custom.js

plugins:
  - search

